apiVersion: argoproj.io/v1alpha1

kind: Application


metadata:

  name: qoves-namespace

  namespace: argocd



spec:

  project: default


  source:

    repoURL: https://github.com/Revival-fire/qoves-take-home-assignment.git

    targetRevision: main

    path: gitops/namespaces



  destination:

    server: https://kubernetes.default.svc

    namespace: qoves-app



  syncPolicy:

    automated:

      prune: true

      selfHeal: true