apiVersion: v1

kind: Service

metadata:
  name: qoves-api

  namespace: qoves-app

  labels:
    app: qoves-api

spec:
  selector:
    app: qoves-api

  ports:
    - name: http

      port: 80

      targetPort: 5000
