apiVersion: monitoring.coreos.com/v1

kind: ServiceMonitor

metadata:
  name: qoves-api-monitor

  namespace: qoves-app

spec:
  selector:
    matchLabels:
      app: qoves-api

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
